apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rebuild_wheels
  annotations:
    github.com/project-slug: imZTY/rebuild_wheels
spec:
  type: other
  lifecycle: unknown
  owner: imZTY
